TXAD-154: Fix Upload Photo issue of Report New QA Screen.
objectorientguy/toolkitx pull request #101
Opened 2023-08-21 12:43 UTC by ruchawajpe

2023-08-24 04:46 UTC, objectorientguy requested changes

2023-08-24 04:46 UTC, objectorientguy commented on lib/blocs/pickAndUploadImage/pick_and_upload_image_bloc.dart
> +    number = 0;
What is number? Page Number? Mobile Number? House Number? Plot Number? 🤔

2023-08-24 04:46 UTC, objectorientguy commented on lib/blocs/pickAndUploadImage/pick_and_upload_image_bloc.dart
>      isInitial = true;
What is isInitial? What is this variable talking about?

2023-08-24 04:46 UTC, objectorientguy commented on lib/blocs/pickAndUploadImage/pick_and_upload_image_bloc.dart
>          bool isAttached = false;
isAttached - emotions, money, feelings, image, pdf? What is attached? 🤔

2023-08-24 08:58 UTC, ruchawajpe commented on lib/blocs/pickAndUploadImage/pick_and_upload_image_bloc.dart
> +    number = 0;
It's the increment number of the image. For eg: if 1 image is uploaded, number will be 1, if 2 images are uploaded the number will be 2 etc.

2023-08-24 08:59 UTC, ruchawajpe commented on lib/blocs/pickAndUploadImage/pick_and_upload_image_bloc.dart
>      isInitial = true;
It tells if we are adding image for the first time.Eg: Initial State.

2023-08-24 10:15 UTC, objectorientguy requested changes

2023-08-24 10:15 UTC, objectorientguy commented on lib/blocs/pickAndUploadImage/pick_and_upload_image_bloc.dart
> +  bool isUploadInitial = true;
isUploadInitial -> isInitialUpload 
imageNumber -> imageIndex

2023-09-04 07:52 UTC, ruchawajpe commented on lib/blocs/pickAndUploadImage/pick_and_upload_image_bloc.dart
> +  bool isUploadInitial = true;
Done

2023-09-19 13:39 UTC, objectorientguy approved these changes

2023-09-19 13:54 UTC, merged