TXAD-163 Implemented Loto List and Filters
objectorientguy/toolkitx pull request #137
Opened 2023-09-20 07:39 UTC by 404ajayreddy

2023-09-20 07:59 UTC, Aditi-005 requested changes

2023-09-20 07:59 UTC, Aditi-005 commented on lib/screens/loto/widgets/loto_location_filter.dart
> +                      await Navigator.push(
use app route

2023-09-20 07:59 UTC, Aditi-005 commented on lib/screens/loto/widgets/loto_location_list.dart
> +  final List data;
what is this data?

2023-09-21 04:16 UTC, ruchawajpe approved these changes

2023-09-21 06:28 UTC, Aditi-005 approved these changes

2023-09-21 06:54 UTC, merged