TXAD-1: Refactor OnBoarding module.
objectorientguy/toolkitx pull request #18
Opened 2023-05-22 09:36 UTC by ruchawajpe

2023-05-22 12:37 UTC, objectorientguy requested changes
Requested changes

2023-05-22 12:37 UTC, objectorientguy commented on lib/blocs/dateFormat/save_date_format_bloc.dart
> +class SaveDateFormatBloc extends Bloc<SaveDateFormatEvent, DateFormatSaved> {
Change SaveDateFormatBloc to DateFormatBloc

2023-05-22 12:37 UTC, objectorientguy commented on lib/blocs/dateFormat/save_date_format_bloc.dart
> +      _customerCache.setCustomerDateFormatString(
why to we need string in the name?

2023-05-22 12:37 UTC, objectorientguy commented on lib/blocs/dateFormat/save_date_format_event.dart
> +class SaveDateFormatEvent {
Rename to DateFormatEvent

2023-05-22 12:37 UTC, objectorientguy commented on lib/blocs/dateFormat/save_date_format_state.dart
> +class DateFormatSaved {}
Rename to DateFormatState

2023-05-22 12:37 UTC, objectorientguy commented on lib/screens/onboarding/selectDateFormat/select_date_format_screen.dart
Did we not try with bloc? Lets not use stateful widgets

2023-05-22 12:37 UTC, objectorientguy commented on lib/screens/onboarding/widgets/type_expansion_tile.dart
Try with Bloc

2023-05-25 12:30 UTC, objectorientguy requested changes

2023-05-27 07:02 UTC, objectorientguy approved these changes

2023-05-27 07:03 UTC, objectorientguy commented on lib/widgets/generic_app_bar.dart
> +  final String textValue;
still not done?

2023-05-27 07:03 UTC, objectorientguy commented on lib/blocs/dateFormat/date_format_states.dart
> +class DateFormatInitial extends DateFormatStates {}
hello? can you hear me?

2023-05-27 07:04 UTC, objectorientguy commented on lib/blocs/dateFormat/date_format_events.dart
> +class DateFormatEvent {
????

2023-05-27 07:05 UTC, objectorientguy commented on lib/blocs/dateFormat/date_format_bloc.dart
> +  FutureOr<void> _saveDateFormatValue(
hello??

2023-05-27 07:46 UTC, ruchawajpe commented on lib/blocs/dateFormat/date_format_bloc.dart
> +  FutureOr<void> _saveDateFormatValue(
This change is updated.

2023-05-27 07:46 UTC, ruchawajpe commented on lib/blocs/dateFormat/date_format_events.dart
> +class DateFormatEvent {
This change is updated.

2023-05-27 07:46 UTC, ruchawajpe commented on lib/blocs/dateFormat/date_format_states.dart
> +class DateFormatInitial extends DateFormatStates {}
This change is updated.

2023-05-27 08:03 UTC, ruchawajpe commented on lib/widgets/generic_app_bar.dart
> +  final String textValue;
This change is reflected.

2023-05-27 08:04 UTC, ruchawajpe commented on lib/blocs/dateFormat/date_format_states.dart
> +class DateFormatInitial extends DateFormatStates {}
This change is reflected.

2023-05-27 08:04 UTC, ruchawajpe commented on lib/blocs/dateFormat/save_date_format_bloc.dart
> +class SaveDateFormatBloc extends Bloc<SaveDateFormatEvent, DateFormatSaved> {
This change is updated.

2023-05-27 08:17 UTC, merged