TXAD-1: Implement Language, Time Zone and Login API.
objectorientguy/toolkitx pull request #20
Opened 2023-05-27 11:53 UTC by Aditi-005

2023-05-27 12:06 UTC, objectorientguy requested changes

2023-05-27 12:06 UTC, objectorientguy commented on lib/blocs/login/login_bloc.dart
> +    on<UserTypeDropDown>(_userTypeValueChanged);
Rename UserTypeDropdown to UserType

2023-05-27 12:06 UTC, objectorientguy commented on lib/blocs/login/login_bloc.dart
Check overall naming conventions. For ex :

GenerateOtpLoginLoaded to OTPGenerated and so on...

2023-05-27 18:11 UTC, objectorientguy requested changes

2023-05-27 18:11 UTC, objectorientguy commented on lib/blocs/login/login_bloc.dart
> +      GenerateLoginOtpModel generateOtpLoginModel =
generateOtpLoginModel ? or generateLoginOtpModel ? 

And anyways you are always going to generate otp for login, so you can say generateOtpModel! Also for rest of the fucntions

2023-05-27 18:11 UTC, objectorientguy commented on lib/screens/onboarding/widgets/language_initializing.dart
> +                height: kLanguagePopUpHeight,
This should be pop up height and not languagePopUpHeight. Make this as a common pop up.

2023-05-27 18:11 UTC, objectorientguy commented on lib/screens/onboarding/widgets/select_language_body.dart
> +                          top: kLanguageFlagPadding,
I dont want padding according to LanguageFlag. It should be generic

2023-05-27 18:11 UTC, objectorientguy commented on lib/configs/app_dimensions.dart
> +const double kLanguagePopUpWidth = 220;
See if you can keep it generic and not language / tags something like this.

2023-05-29 08:45 UTC, ruchawajpe commented on lib/blocs/language/language_bloc.dart
> +    emit(DownLoadLanguageLoading());
Cool!

2023-05-31 04:03 UTC, objectorientguy approved these changes

2023-06-01 06:47 UTC, ruchawajpe commented on lib/screens/onboarding/language/select_language_screen.dart
> +                      context, StringConstants.kSelectLanguageAgain, '');
Add kOk ----> ' '

2023-06-01 14:45 UTC, ruchawajpe approved these changes

2023-06-01 14:47 UTC, merged