TXAD-19: Add permit user interface
objectorientguy/toolkitx pull request #22
Opened 2023-05-29 11:50 UTC by objectorientguy

2023-05-29 12:17 UTC, Aditi-005 requested changes
Please make the requested changes

2023-05-29 12:17 UTC, Aditi-005 commented on lib/screens/home/widgets/online_modules.dart
> +        Navigator.pushNamed(context, PermitScreen.routeName);
Why not PermitListScreen?

2023-05-29 12:17 UTC, Aditi-005 commented on lib/screens/permit/permit_details_screen.dart
> +                        width: MediaQuery.of(context).size.width * 0.25,
why not defined in app dimensions

2023-05-29 12:17 UTC, Aditi-005 commented on lib/screens/permit/permit_details_screen.dart
> +              thickness: 1,
why not in app dimensions

2023-05-29 12:17 UTC, Aditi-005 commented on lib/screens/permit/permit_screen.dart
> +                                width: MediaQuery.of(context).size.width * 0.25,
why not defined in app dimensions

2023-05-29 12:17 UTC, Aditi-005 commented on lib/screens/permit/permit_screen.dart
> +                                  borderRadius: BorderRadius.circular(5),
why not defined in app dimensions

2023-05-29 12:17 UTC, Aditi-005 commented on lib/screens/permit/widgets/permit_group.dart
> +                      width: MediaQuery.of(context).size.width * 0.15,
why not defined in app dimensions

2023-05-29 12:17 UTC, Aditi-005 commented on lib/screens/permit/widgets/tags.dart
> +            borderRadius: BorderRadius.circular(5),
why not defined in app dimensions

2023-05-29 12:17 UTC, Aditi-005 commented on lib/screens/permit/widgets/tags.dart
> +          margin: const EdgeInsets.only(right: 5, bottom: 5),
why not defined in app dimensions

2023-05-29 12:17 UTC, Aditi-005 commented on lib/screens/permit/widgets/tags.dart
> +            padding: EdgeInsets.all(8.0),
why not defined in app dimensions

2023-05-29 12:17 UTC, Aditi-005 commented on lib/screens/permit/widgets/tags.dart
> +            borderRadius: BorderRadius.circular(5),
why not defined in app dimensions

2023-05-29 12:17 UTC, Aditi-005 commented on lib/screens/permit/widgets/tags.dart
> +          margin: const EdgeInsets.only(right: 5, bottom: 5),
why not defined in app dimensions

2023-05-29 12:17 UTC, Aditi-005 commented on lib/screens/permit/widgets/tags.dart
> +            padding: EdgeInsets.all(8.0),
why not defined in app dimensions

2023-05-29 12:17 UTC, Aditi-005 commented on lib/screens/permit/widgets/tags.dart
> +            borderRadius: BorderRadius.circular(5),
why not defined in app dimensions

2023-05-30 10:03 UTC, objectorientguy commented on lib/screens/permit/widgets/tags.dart
> +            borderRadius: BorderRadius.circular(5),
Done

2023-05-30 10:06 UTC, objectorientguy commented on lib/screens/permit/widgets/tags.dart
> +            padding: EdgeInsets.all(8.0),
Done

2023-05-30 10:06 UTC, objectorientguy commented on lib/screens/permit/widgets/tags.dart
> +          margin: const EdgeInsets.only(right: 5, bottom: 5),
Done

2023-05-30 10:07 UTC, objectorientguy commented on lib/screens/permit/widgets/tags.dart
> +            borderRadius: BorderRadius.circular(5),
Done

2023-05-30 10:07 UTC, objectorientguy commented on lib/screens/permit/widgets/tags.dart
> +            padding: EdgeInsets.all(8.0),
Done

2023-05-30 10:07 UTC, objectorientguy commented on lib/screens/permit/permit_screen.dart
> +                                  borderRadius: BorderRadius.circular(5),
As discussed in the daily call. This container contains a dynamic data which cant be defined in app dimensions.
As name defines 'app dimensions' has all the defined variables which are consistently used in the app through out.

2023-05-30 10:07 UTC, objectorientguy commented on lib/screens/permit/permit_details_screen.dart
> +              thickness: 1,
Done

2023-05-30 10:31 UTC, objectorientguy commented on lib/screens/home/widgets/online_modules.dart
> +        Navigator.pushNamed(context, PermitScreen.routeName);
Its the default screen of that module, so wanted to keep it this way. 
But yeah, can make it PermitListScreen.

2023-05-30 10:45 UTC, Aditi-005 commented on lib/screens/permit/permit_details_screen.dart
> +                        width: MediaQuery.of(context).size.width * 0.25,
Ok

2023-05-30 10:53 UTC, Aditi-005 requested changes
Please make the changes

2023-05-30 10:53 UTC, Aditi-005 commented on lib/screens/permit/widgets/permit_timeline.dart
> +            Image.asset('assets/icons/clock.png', height: 15, width: 15),
Add height and width in app dimensions

2023-05-30 10:53 UTC, Aditi-005 commented on lib/screens/permit/widgets/permit_timeline.dart
> +            Image.asset('assets/icons/calendar.png', height: 15, width: 15),
Add height and width in app dimensions

2023-05-30 11:02 UTC, Aditi-005 approved these changes
Approved

2023-05-30 13:12 UTC, merged