TXAD-19: Implement permit list APIs
objectorientguy/toolkitx pull request #23
Opened 2023-05-30 20:11 UTC by objectorientguy

2023-06-01 04:10 UTC, Aditi-005 requested changes
Please make the requested changes

2023-06-01 04:10 UTC, Aditi-005 commented on lib/screens/permit/permit_details_screen.dart
> +                // subtitle: const Padding(
Remove commented code

2023-06-01 04:10 UTC, Aditi-005 commented on lib/screens/permit/widgets/permit_details.dart
> +        // const DateTimeRow(),
Remove commented code

2023-06-01 04:10 UTC, Aditi-005 commented on lib/widgets/icon_and_text_row.dart
> +  final String? title;
no need to make it nullable

2023-06-01 04:10 UTC, Aditi-005 commented on lib/widgets/icon_and_text_row.dart
> +        Text(title!)
remove null check

2023-06-01 13:02 UTC, objectorientguy commented on lib/data/models/status_tag_model.dart
> +  final String? title;
done

2023-06-01 13:03 UTC, objectorientguy commented on lib/screens/permit/widgets/permit_details.dart
> +        // const DateTimeRow(),
done

2023-06-01 13:03 UTC, objectorientguy commented on lib/widgets/icon_and_text_row.dart
> +        Text(title!)
why?

2023-06-01 13:03 UTC, objectorientguy commented on lib/widgets/icon_and_text_row.dart
> +  final String? title;
why?

2023-06-02 02:16 UTC, Aditi-005 commented on lib/widgets/icon_and_text_row.dart
> +  final String? title;
If you have already assigned initial value as "" then it won't ever be "null".  Its basically not in use at all, and you had to give an unnecessary null check

2023-06-02 02:17 UTC, Aditi-005 commented on lib/widgets/icon_and_text_row.dart
> +        Text(title!)
If you have already assigned initial value as "" then it won't ever be "null". Its an unnecessary null check

2023-06-02 05:39 UTC, Aditi-005 approved these changes
Approved

2023-06-02 05:41 UTC, merged