TXAD-89: Implement Get and Post API for Checklist System User.
objectorientguy/toolkitx pull request #32
Opened 2023-06-15 13:34 UTC by ruchawajpe

2023-06-16 11:17 UTC, Aditi-005 requested changes
Please do the changes.

2023-06-16 11:17 UTC, Aditi-005 commented on lib/blocs/checklist/systemUser/pdf/sys_user_pdf_bloc.dart
> +          "SvwH32gnWK1slqvskIsSg9duoVfgOQLWitcfZGr+n2KX1yltKm2T+EbsIhBm0E6B");
Get this from shared prefs

2023-06-16 11:17 UTC, Aditi-005 commented on lib/screens/checklist/systemUser/widgets/sys_user_list_section.dart
> +              showCustomSnackBar(context, 'Load more...', '');
Add in string constants

2023-06-16 11:17 UTC, Aditi-005 commented on lib/screens/checklist/systemUser/widgets/sys_user_list_section.dart
> +              showCustomSnackBar(context, 'No more data!', '');
Add in string constants

2023-06-16 11:17 UTC, Aditi-005 commented on lib/utils/pdf_encrypt_data.dart
> +
Remove file, this function is done in encrypt file already

2023-06-17 05:13 UTC, ruchawajpe commented on lib/blocs/checklist/systemUser/approvePopUp/sys_user_approve_pop_up_bloc.dart
> +class ApproveBloc extends Bloc<ApproveEvent, ApproveStates> {
CheckList

2023-06-20 13:00 UTC, Aditi-005 commented on lib/blocs/checklist/systemUser/pdf/sys_user_checklist_pdf_events.dart
> +class FetchCheckListPdf {
FetchCheckListPdf to FetchCheckListPdfEvent

2023-06-20 13:03 UTC, Aditi-005 commented on lib/blocs/checklist/systemUser/scheduleDatesResponse/checklist_schedule_dates_response_bloc.dart
> +      'Approve',
User database keys

2023-06-20 13:10 UTC, Aditi-005 commented on lib/screens/checklist/systemUser/sys_user_pop_up_menu_screen.dart
> +                  if (value == 'Approve') {
user database keys

2023-06-20 13:12 UTC, Aditi-005 commented on lib/screens/checklist/systemUser/widgets/sys_user_list_section.dart
> +                                        '${checklistData[index].categoryname} -- ${checklistData[index].subcategoryname.toString()}',
remove .toString()

2023-06-20 13:45 UTC, Aditi-005 approved these changes
Approved!

2023-06-20 13:48 UTC, merged