TXAD-14: Implement Incident Details API to Incident Tab 1 and Tab 2.
objectorientguy/toolkitx pull request #44
Opened 2023-06-29 06:36 UTC by ruchawajpe

2023-07-01 06:15 UTC, objectorientguy requested changes

2023-07-03 05:11 UTC, ruchawajpe commented on lib/blocs/incident/incidentDetails/incident_details_bloc.dart
> +      String hashCode = (await _customerCache.getHashCode(CacheKeys.hashcode))!;
Yes, I have added a null aware operator for the declared variable. I have confirmed it from Aditi if any of the values are null it is getting handled in the client module itself.

2023-07-03 05:12 UTC, ruchawajpe commented on lib/main.dart
> +          BlocProvider(lazy: false, create: (context) => IncidentDetailsBloc()),
Done with the requested change.

2023-07-04 10:22 UTC, Aditi-005 requested changes

2023-07-04 10:22 UTC, Aditi-005 commented on lib/screens/incident/widgets/view_incident_details_network_image.dart
> +            childAspectRatio: 180 / 180,
remove this as its output will be 1

2023-07-04 10:48 UTC, Aditi-005 approved these changes

2023-07-04 11:00 UTC, merged