TXAD-26 Implemented Logbook List Screen
objectorientguy/toolkitx pull request #70
Opened 2023-07-11 08:49 UTC by 404ajayreddy

2023-07-11 14:19 UTC, ruchawajpe requested changes

2023-07-11 14:19 UTC, ruchawajpe commented on lib/blocs/LogBook/logbook_events.dart
> +abstract class LogbookEvents {}
Remove abstract class. If you have more that one event use abstract class.

2023-07-11 14:19 UTC, ruchawajpe commented on lib/screens/logBook/logbook_list_screen.dart
> +        title: 'Report a Log',
Check if we get the key for it else use String constants.

2023-07-12 10:57 UTC, 404ajayreddy commented on lib/blocs/LogBook/logbook_states.dart
> +class LogbookFetchError extends LogbookStates {}
Need it for the bloc emit

2023-07-12 10:57 UTC, 404ajayreddy commented on lib/screens/logBook/widgets/logbook_list.dart
> +        if (state is LogbookFetchError) {
Removed

2023-07-12 10:59 UTC, 404ajayreddy commented on lib/blocs/LogBook/logbook_events.dart
> +abstract class LogbookEvents {}
Will have a post event here for add log screen So need it

2023-07-12 11:02 UTC, 404ajayreddy commented on lib/screens/logBook/logbook_list_screen.dart
> +        title: 'Report a Log',
done

2023-07-12 11:18 UTC, ruchawajpe commented on lib/blocs/LogBook/logbook_events.dart
> +abstract class LogbookEvents {}
Alright

2023-07-12 11:19 UTC, ruchawajpe commented on lib/blocs/LogBook/logbook_states.dart
> +class LogbookFetchError extends LogbookStates {}
Alright!

2023-07-12 11:19 UTC, ruchawajpe approved these changes

2023-07-12 11:38 UTC, merged