TXAD-2: Implement Profile module
objectorientguy/toolkitx pull request #8
Opened 2023-05-15 10:22 UTC by ruchawajpe

2023-05-15 10:48 UTC, objectorientguy requested changes

2023-05-15 10:48 UTC, objectorientguy commented on lib/screens/onboarding/login/password/password_screen.dart
rename cyan

2023-05-15 10:48 UTC, objectorientguy commented on lib/screens/onboarding/selectDateFormat/select_date_format_screen.dart
define colors in colors util class

2023-05-15 10:48 UTC, objectorientguy commented on lib/screens/profile/widgets/edit_options.dart
have common radius

2023-05-15 10:48 UTC, objectorientguy commented on lib/screens/profile/widgets/options_class.dart
why under screens folder?

2023-05-15 10:48 UTC, objectorientguy commented on lib/screens/profile/widgets/profile_options.dart
final String email = Uri.encodeComponent(
                              StringConstants.kToolkitXEmail);
                          Uri mail = Uri.parse("mailto:$email"); 
                          
                          could be improved

2023-05-15 10:48 UTC, objectorientguy commented on lib/screens/profile/widgets/profile_options.dart
overall code could be optimised

2023-05-15 10:48 UTC, objectorientguy commented on lib/utils/profile_util.dart
could be optimised

2023-05-15 10:48 UTC, objectorientguy commented on lib/widgets/generic_app_bar.dart
define size in common

2023-05-15 11:52 UTC, ruchawajpe reviewed
Please review the changes.

2023-05-15 18:16 UTC, objectorientguy requested changes

2023-05-15 18:16 UTC, objectorientguy commented on lib/data/models/options_class.dart
Class name should match with the file name.

2023-05-15 18:16 UTC, objectorientguy commented on lib/screens/onboarding/login/emailAddress/login_screen.dart
Route name is different than Login Screen

2023-05-15 18:16 UTC, objectorientguy commented on lib/screens/onboarding/login/emailAddress/login_screen.dart
Padding(
                                  padding: EdgeInsets.all(
                                      MediaQuery.of(context).size.width *
                                          0.042),
                                          

Why? When we have already defined the padding

2023-05-15 18:16 UTC, objectorientguy commented on lib/screens/onboarding/login/password/password_screen.dart
Icon(Icons.lock,
                            size: MediaQuery.of(context).size.width * 0.1)),
                            
                            
why media query when we have already defined the size in app config

2023-05-15 18:16 UTC, objectorientguy commented on lib/screens/onboarding/selectDateFormat/select_date_format_screen.dart
dateFormat: dateFormatValues.toString()));
   
   why toString()?

2023-05-15 18:16 UTC, objectorientguy commented on lib/screens/profile/profile_screen.dart
why there is no route name?

2023-05-17 05:12 UTC, objectorientguy requested changes

2023-05-17 05:12 UTC, objectorientguy commented on lib/screens/profile/widgets/logout.dart
Keep cupertino for iOS and normal pop up for android

2023-05-17 08:46 UTC, Aditi-005 requested changes

2023-05-17 08:46 UTC, Aditi-005 commented on lib/widgets/android_pop_up.dart
> +        actions: <Widget>[
Remove "Widget" from actions

2023-05-17 08:50 UTC, Aditi-005 approved these changes

2023-05-17 09:55 UTC, objectorientguy requested changes

2023-05-17 09:55 UTC, objectorientguy commented on lib/screens/profile/widgets/edit_options_section.dart
change imagePath location

2023-05-17 09:55 UTC, objectorientguy commented on lib/widgets/ios_pop_up.dart
use the data of constructor

2023-05-17 12:32 UTC, Aditi-005 approved these changes

2023-05-17 13:12 UTC, objectorientguy requested changes

2023-05-18 06:44 UTC, objectorientguy requested changes

2023-05-18 06:44 UTC, objectorientguy commented on lib/screens/onboarding/login/password/password_screen.dart
> +                                    const TextFieldWidget(maxLines: 1),
max lines 1 can be by default in Textfieldwidget

2023-05-18 06:44 UTC, objectorientguy commented on lib/utils/profile_util.dart
> +  static const String imageIconPath = 'assets/icons/';
missed? or have different opinion?

2023-05-18 07:08 UTC, objectorientguy approved these changes

2023-05-18 07:10 UTC, objectorientguy approved these changes

2023-05-18 07:31 UTC, merged