TXAD-127: Implement filter to Quality Management Filters screen.
objectorientguy/toolkitx pull request #93
Opened 2023-08-02 06:51 UTC by ruchawajpe

2023-08-03 04:25 UTC, Aditi-005 approved these changes

2023-08-03 04:33 UTC, objectorientguy requested changes

2023-08-03 04:33 UTC, objectorientguy commented on lib/screens/qualityManagement/qm_list_screen.dart
>  class QualityManagementListScreen extends StatefulWidget {
Why is it a stateful widget, and why is it approved @Aditi-005  ?

2023-08-03 04:33 UTC, objectorientguy commented on lib/screens/qualityManagement/widgets/qm_status_filter.dart
> +class QualityManagementStatusFilter extends StatefulWidget {
As mentioned above, why stateful?

2023-08-03 15:49 UTC, ruchawajpe commented on lib/screens/qualityManagement/qm_list_screen.dart
>  class QualityManagementListScreen extends StatefulWidget {
Pagination is implemented to this screen.

2023-08-05 06:30 UTC, ruchawajpe commented on lib/screens/qualityManagement/widgets/qm_status_filter.dart
> +class QualityManagementStatusFilter extends StatefulWidget {
Implemented it with bloc.

2023-08-07 04:16 UTC, objectorientguy approved these changes

2023-08-07 04:48 UTC, merged